# Prep for TERp

In [13]:
import pandas as pd
from data_helpers import remove_special_characters

In [16]:
df = pd.read_csv(path + 'test-df.csv')
terp_ref = []
terp_hyp = []
for i in range(len(df)):
    s0, s1 = remove_special_characters(df.iloc[i, 0]), remove_special_characters(
                df.iloc[i, 1])
    annotation = ' ([kle][msrp][{index}])' 
    terp_ref.append(s0 + annotation.format(index=i*2)) 
    terp_hyp.append(s1 + annotation.format(index=i*2))
    terp_ref.append(s1 + annotation.format(index=i*2+1))
    terp_hyp.append(s0 + annotation.format(index=i*2+1))

In [17]:
with open("C:\\Users\\leva\\Thesis\\Data\\MSRP\\test.terp.hyp.trans", 'w') as f:
    f.write("\n".join(map(str, terp_hyp)))

In [18]:
with open("C:\\Users\\leva\\Thesis\\Data\\MSRP\\test.terp.ref.trans", 'w') as f:
    f.write("\n".join(map(str, terp_ref)))

In [19]:
terp_hyp

['Current Chief Operating Officer Mike Butcher and Group Chief Financial Officer Alex Arena will report to So ([kle][msrp][0])',
 'PCCWs chief operating officer Mike Butcher and Alex Arena the chief financial officer will report directly to Mr So ([kle][msrp][1])',
 'Domestic sales at both GM and No 2 Ford Motor Co declined more than predicted as a late summer sales frenzy prompted a largerthanexpected industry backlash ([kle][msrp][2])',
 'The worlds two largest automakers said their US sales declined more than predicted last month as a late summer sales frenzy caused more of an industry backlash than expected ([kle][msrp][3])',
 'The Centers for Disease Control and Prevention said there were 19 reported cases of measles in the United States in 2002 ([kle][msrp][4])',
 'According to the federal Centers for Disease Control and Prevention news  web sites there were 19 reported cases of measles in the United States in 2002 ([kle][msrp][5])',
 'A tropical storm rapidly developed in the Gu

# Get Embeddings and Additional Features

In [1]:
from data import Data
import pickle
import numpy as np

In [2]:
path = "C:\\Users\\leva\\Thesis\\Data\\MSRP\\"

In [3]:
train = Data()
train.open_and_preprocess(path=path, mode="train")


Removing special chars & stopwords


In [5]:
train.get_embeddings(embedding_type="word2vec")

Getting embeddings


C:\Users\leva\thesis\thesis_venv\lib\site-packages\nltk\translate\bleu_score.py:516: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
C:\Users\leva\thesis\thesis_venv\lib\site-packages\nltk\translate\bleu_score.py:516: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
C:\Users\leva\thesis\thesis_venv\lib\site-packages\nltk\translate\bleu_score.py:516: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use Smoo

Getting embeddings for pair 100 out of 3669
Getting embeddings for pair 200 out of 3669
Getting embeddings for pair 300 out of 3669
Getting embeddings for pair 400 out of 3669
Getting embeddings for pair 500 out of 3669
Getting embeddings for pair 600 out of 3669
Getting embeddings for pair 700 out of 3669
Getting embeddings for pair 800 out of 3669
Getting embeddings for pair 900 out of 3669
Getting embeddings for pair 1000 out of 3669
Getting embeddings for pair 1100 out of 3669
Getting embeddings for pair 1200 out of 3669
Getting embeddings for pair 1300 out of 3669
Getting embeddings for pair 1400 out of 3669
Getting embeddings for pair 1500 out of 3669
Getting embeddings for pair 1600 out of 3669
Getting embeddings for pair 1700 out of 3669
Getting embeddings for pair 1800 out of 3669
Getting embeddings for pair 1900 out of 3669
Getting embeddings for pair 2000 out of 3669
Getting embeddings for pair 2100 out of 3669
Getting embeddings for pair 2200 out of 3669
Getting embeddings 

In [9]:
train.max_len

35

In [7]:
pickle.dump(train.embedded,  open( "C:\\Users\\leva\\Thesis\\Data\\MSRP\\train_with_BLEU_NIST_METEOR_ROUGE_TERp_len0_len1.p", "wb" ))

In [8]:
val = Data()
val.open_and_preprocess(path=path, mode="val")
val.max_len=train.max_len
val.get_embeddings(embedding_type="word2vec")
len(val.embedded[0][0][0])

Removing special chars & stopwords
Getting embeddings
Getting embeddings for pair 100 out of 409
Getting embeddings for pair 200 out of 409
Getting embeddings for pair 300 out of 409
Getting embeddings for pair 400 out of 409


In [11]:
pickle.dump(val.embedded,  open( "C:\\Users\\leva\\Thesis\\Data\\MSRP\\val_with_BLEU_NIST_METEOR_ROUGE_TERp_len0_len1.p", "wb" ))

In [14]:
test = Data()
test.open_and_preprocess(path=path, mode="test")
test.max_len=train.max_len
test.get_embeddings(embedding_type="word2vec")

Removing special chars & stopwords
Getting embeddings
Getting embeddings for pair 100 out of 1726
Getting embeddings for pair 200 out of 1726
Getting embeddings for pair 300 out of 1726
Getting embeddings for pair 400 out of 1726
Getting embeddings for pair 500 out of 1726
Getting embeddings for pair 600 out of 1726
Getting embeddings for pair 700 out of 1726
Getting embeddings for pair 800 out of 1726
Getting embeddings for pair 900 out of 1726
Getting embeddings for pair 1000 out of 1726
Getting embeddings for pair 1100 out of 1726
Getting embeddings for pair 1200 out of 1726
Getting embeddings for pair 1300 out of 1726
Getting embeddings for pair 1400 out of 1726
Getting embeddings for pair 1500 out of 1726
Getting embeddings for pair 1600 out of 1726
Getting embeddings for pair 1700 out of 1726


In [15]:
len(val.embedded[0][0][0])

35

In [16]:
test.embedded

[[array([[ 0.07226562, -0.29101562, -0.05517578, ...,  0.        ,
           0.        ,  0.        ],
         [-0.18066406,  0.17871094, -0.06591797, ...,  0.        ,
           0.        ,  0.        ],
         [-0.10449219,  0.05004883,  0.23144531, ...,  0.        ,
           0.        ,  0.        ],
         ...,
         [ 0.33398438, -0.02282715, -0.07714844, ...,  0.        ,
           0.        ,  0.        ],
         [ 0.125     ,  0.11767578,  0.17773438, ...,  0.        ,
           0.        ,  0.        ],
         [-0.20507812,  0.35351562,  0.23925781, ...,  0.        ,
           0.        ,  0.        ]], dtype=float32),
  array([[-0.31445312,  0.09326172, -0.1875    , ...,  0.        ,
           0.        ,  0.        ],
         [-0.09619141, -0.14746094, -0.05883789, ...,  0.        ,
           0.        ,  0.        ],
         [ 0.07714844,  0.23632812, -0.234375  , ...,  0.        ,
           0.        ,  0.        ],
         ...,
         [ 0.167968

In [17]:
pickle.dump(test.embedded,  open( "C:\\Users\\leva\\Thesis\\Data\\MSRP\\test_with_BLEU_NIST_METEOR_ROUGE_TERp_len0_len1.p", "wb" ))

In [74]:
ready_data = list(map(list, zip(*train.embedded)))
x = [np.array(ready_data[0]), np.array(ready_data[1])]
y = np.array(ready_data[2])

In [76]:
y[:, -1]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0.,
       1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1.,
       1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0.,
       1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0.

In [10]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [73]:
np.array(ready_data[2])


array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        1.20000000e+001, 1.50000000e+001, 1.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        1.50000000e+001, 1.20000000e+001, 1.00000000e+000],
       [4.16666667e-002, 3.04485485e-155, 2.74257938e-206, ...,
        8.00000000e+000, 8.00000000e+000, 1.00000000e+000],
       ...,
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        6.00000000e+000, 1.00000000e+001, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        8.00000000e+000, 1.00000000e+001, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        1.00000000e+001, 8.00000000e+000, 0.00000000e+000]])

In [77]:
x = [np.array(ready_data[0]), np.array(ready_data[1])]
y = np.array(ready_data[2])
tensor_x = torch.Tensor(x).permute(1, 0, 3, 2)
tensor_y = torch.Tensor(y)


In [78]:
tensor_dataset = TensorDataset(tensor_x, tensor_y)
data_loader = DataLoader(dataset=tensor_dataset, batch_size=128, shuffle=True)


In [79]:
for data, labels in data_loader:
    features = labels[:,0:-1]
    scores = labels[:,-1].unsqueeze(1)
    print(scores)

tensor([[1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [48]:
from sklearn.metrics import classification_report
y_true = [0, 1, 0, 0, 1, 0]
y_pred = [0, 1, 1, 0, 0, 1]
a = classification_report(y_true, y_pred, output_dict = True)

In [49]:
a

{'0': {'precision': 0.6666666666666666,
  'recall': 0.5,
  'f1-score': 0.5714285714285715,
  'support': 4},
 '1': {'precision': 0.3333333333333333,
  'recall': 0.5,
  'f1-score': 0.4,
  'support': 2},
 'accuracy': 0.5,
 'macro avg': {'precision': 0.5,
  'recall': 0.5,
  'f1-score': 0.48571428571428577,
  'support': 6},
 'weighted avg': {'precision': 0.5555555555555555,
  'recall': 0.5,
  'f1-score': 0.5142857142857143,
  'support': 6}}

In [45]:
a.get('0').get('f1-score')

0.5714285714285715

In [18]:
import pandas as pd

In [29]:
df = pd.read_csv('C:/Users/leva/Thesis/Models/ABCNN3/MSRP/WithAdditionalFeatures/Local/211102/logs.csv')

In [32]:
epoch_metrics = {'epoch': 1, 
           'train_loss': 2, 
           'train_accuracy': 3,
           'train_f1_0': 4, 
           'train_f1_1': 5,
           'val_accuracy': 6, 
           'val_loss': 7,
           'val_f1_0': 8,
           'val_f1_1': 9}

In [33]:
df = df.append(epoch_metrics, ignore_index=True)

In [34]:
df

epoch  train_loss  train_accuracy  train_f1_0  train_f1_1  val_loss  \
0      7    0.500303        0.812704    0.751177    0.849836  0.626200   
1      8    0.488699        0.837650    0.772667    0.873741  0.593633   
2      9    0.469178        0.847328    0.786015    0.881331  0.633360   
3     10    0.458881        0.866412    0.803607    0.898781  0.602662   
4     11    0.443082        0.864913    0.760570    0.905915  0.613447   
5     12    0.427785        0.855643    0.803561    0.885896  0.696372   
6     13    0.421361        0.895038    0.834480    0.923154  0.635220   
7     14    0.401387        0.904853    0.853484    0.929552  0.683552   
8     15    0.390970        0.865458    0.818332    0.893170  0.637099   
9      1    2.000000        3.000000    4.000000    5.000000  7.000000   

   val_accuracy  val_f1_0  val_f1_1  
0      0.697173  0.634983  0.737308  
1      0.725818  0.619410  0.784771  
2      0.706101  0.613729  0.760335  
3      0.722842  0.606539  0.785218  
4      0.711310  0.468456  0.798398  
5      0.702753  0.602352  0.758609  
6      0.710938  0.563932  0.782959  
7      0.740327  0.606773  0.805188  
8      0.636161  0.575808  0.677580  
9      6.000000  8.000000  9.000000